hw 22
BobJ0hnson/python-course pull request #9
Opened 2023-02-21 20:35 UTC by BobJ0hnson

3 files

2023-02-26 16:41 UTC, klymenok requested changes

2023-02-26 16:41 UTC, klymenok commented on hw22(1)
> +    date
You have a syntax error here: missing a comma sign after `date`

2023-02-26 16:41 UTC, klymenok commented on hw22(2)
> +SELECT purchases.id, purchases.date, user.first_name, user.last_name
When you join a table, you should use any reference to this table by its name or alias. In your case, you joined `users`, this means that you should reference its name like `users.first_name` and `users.last_name`

2023-02-26 16:41 UTC, klymenok commented on hw22(3)
> +ORDER BY user_id;
`user_id` here is a value from `purchases` which is not taken to the result. Use `users.id` here instead

2023-03-19 17:25 UTC, acman approved these changes

2023-03-24 20:52 UTC, merged